Repository plone/documentation, pull requests merged in 2022-02, with the labels that each got.

#1171 Improve the upgrade guide
  docs/backend/upgrading/v60.md
Labels: 24 status: ready, 99 tag: Plone 6.x

#1183 Add PR template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: 04 type: enhancement, 99 tag: Plone 6.x

#1189 Volto docs use a prefix of "docs-" on all make targets
  docs/contributing/index.md
Labels: 01 type: bug, 99 tag: Plone 6.x
