Repository plone/documentation, pull requests merged in 2025-03, with the labels that each got.

#1874 Add documentation on how to customize containers with custom files
  docs/install/containers/index.md
  docs/install/containers/recipes/index.md
Labels: 04 type: enhancement

#1895 Fix reference to Classic UI theming
  docs/classic-ui/static-resources.md
Labels: 01 type: bug

#1905 Add support for tooltips, `attrs_block`, `attrs_inline`, and `strikethrough`
  docs/conf.py
  docs/contributing/documentation/myst-reference.md
  docs/contributing/documentation/themes-and-extensions.md
  requirements.txt
Labels: 04 type: enhancement

#1914 Search results with breadcrumbs. Search with filters by section.
  docs/_static/searchtools.js
  docs/_templates/search.html
Labels: 03 type: feature (plip), 12 prio: high

#1926 Add new section, Guidance for merging pull requests
  docs/contributing/index.md
Labels: 04 type: enhancement

#1929 Clean up install with Cookieplone
  Makefile
  docs/_inc/_hardware-requirements.md
  docs/_inc/_install-python-plone61.md
  docs/_inc/_install-uv.md
  docs/backend/subscribers.md
  docs/contributing/documentation/authors.md
  docs/install/create-project-cookieplone.md
Labels: 01 type: bug
